name: Delivery

on: workflow_dispatch # Só será executado manualmente

jobs:

  delivery:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Merge to main
        run: |
          git fetch
          git checkout main
          git merge develop --allow-unrelated-histories --no-edit
          git push origin main
